### ISSUE TITLE
pacman support

### ISSUE THREAD

**Issue by bbigras** [acheronfail/xi-electron#11]
`yarn make` tries to make a deb package on Arch Linux
ea709d6820603a7d18d26b41e098d9000a674bfe

```
% yarn make
yarn run v1.3.2
$ electron-forge make
✔ Checking your system
✔ Resolving Forge Config
We need to package your application before we can make it
✔ Preparing to Package Application for arch: x64
✔ Compiling Application
✔ Preparing native dependencies
✔ Packaging Application
Making for the following targets:
✖ Making for target: deb - On platform: linux - For arch: x64
An unhandled error has occurred inside Forge:
An error occured while making for target: deb
Error executing command (127):
fakeroot dpkg-deb --build /tmp/electron-11815-8910-1gcd7dj.gsmtf/xi-electron-ts_1.0.0_amd64
/usr/bin/fakeroot: ligne 178: dpkg-deb : commande introuvable
Error: Error executing command (127):
fakeroot dpkg-deb --build /tmp/electron-11815-8910-1gcd7dj.gsmtf/xi-electron-ts_1.0.0_amd64
/usr/bin/fakeroot: ligne 178: dpkg-deb : commande introuvable
    at ChildProcess.<anonymous> (/home/bbigras/xi-electron/node_modules/electron-installer-debian/src/installer.js:69:23)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn make  450,05s user 19,63s system 158% cpu 4:57,08 total
```

**Comment by acheronfail** [comment]
I'm not completely familiar with Arch Linux. Do we need to configure it to generate an `rpm`? Or should it be `flatpak` or `snap`?

If it's one of those try running:

```sh
yarn make --platform linux --targets rpm # or flatpak, snap, etc
```

We're currently using [`electron-forge`](https://github.com/electron-userland/electron-forge#possible-make-targets) to package the app - so if it's supported it should be a relatively easy fix :)

**Comment by bbigras** [comment]
> I'm not completely familiar with Arch Linux. Do we need to configure it to generate an rpm? Or should it be flatpak or snap?

It's not rpm. I think `flatpak` or `snap` could be usable but is it possible to build everything in the current directory without creating a package?

An official (or one from the Arch User Repository) would only need to build the files and would create the package itself.

**Comment by acheronfail** [comment]
Ah okay, I see what you mean.

Try just "packaging" the app then, not "making" it ("package" bundles it all together into an executable, whereas "make" packages it and then exports it into an installer, etc).

Run:

```bash
yarn package --platform linux
```

See how that one goes, it should output what you're looking for into `out/xi-electron-linux-x64` :)

**Comment by bbigras** [comment]
It works. Thanks!
