### ISSUE TITLE
Support for GitHub releases

### ISSUE THREAD

**Issue by amilajack** [acheronfail/xi-electron#12]
Would be nice if releases could be uploaded

**Comment by acheronfail** [comment]
Definitely a good idea, I'll have a look into getting Linux and macOS building first (just have to figure out how to get Rust & Node in the same travis build).

Once I've done that I'll see if I can get a Windows build running on appveyor.

**Comment by NyxCode** [comment]
I'd appreciate this since compiling it under windows is pretty painfull.

**Comment by amilajack** [comment]
All the required changes:
https://github.com/amilajack/popcorn-time-desktop/blob/master/package.json#L24
https://github.com/amilajack/popcorn-time-desktop/blob/master/.travis.yml#L79
https://github.com/amilajack/popcorn-time-desktop/blob/master/appveyor.yml#L49

I can PR for this

**Comment by acheronfail** [comment]
Travis builds have improved and are building correctly now (see https://github.com/acheronfail/xi-electron/commit/8523256a267d7a4b82d3277b9559aaf2c6b638dd).

Unfortunately, there's an issue on Travis with Windows builds and having secrets set in Travis, so for now, only Linux and macOS are supported in GitHub releases.

Travis comment here: https://travis-ci.community/t/windows-instances-hanging-before-install/250/2?u=acheronfail

**Comment by acheronfail** [comment]
Going to close this as completed and we'll fix the Windows releases once Travis fixes their bug.
