### ISSUE TITLE
Deprecated node packages

### ISSUE THREAD

**Issue by faraazahmad** [acheronfail/xi-electron#16]
While installing node packages, it shows that some of them are deprecated, 
```
➜  xi-electron git:(master) npm i                  
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
```

Is updating them not a priority right now?

**Comment by acheronfail** [comment]
Those packages are indirect dependencies of this package, so we have no control over whether they are using up-to-date versions or not. 

eg, packages `jade`, `coffee-script`, `constantinople` and `transformers` are children of the dependency `electron-prebuilt-compile`. The others in your list are children of `electron-forge`.

If having all your nested dependencies is important to you, then you'd need to file issues on those repositories to ensure they have their dependencies up-to-date.
