### ISSUE TITLE
Font colour same as background colour in some situations

### ISSUE THREAD

**Issue by ajmalsiddiqui** [acheronfail/xi-electron#17]
In certain situations, the font colour for syntax highlighting matches the background colour, thus making it hard/impossible to read it.

Here's how the issue can be reproduced:
1) build the application using the guidelines in the README
2) Open an instance of the app using `npm start`
3) Type the following in the editor that opens: `if ( x < 200 ) return false`

The word "return" suddenly goes invisible.

Note that just typing `return true` does not replicate the issue.

**Comment by acheronfail** [comment]
Note that this isn't an issue with this repository (xi-electron), but rather an issue with xi-editor itself. This issue should be reported upstream.

See xi-mac: 
<img width="658" alt="screen shot 2018-07-17 at 23 55 41" src="https://user-images.githubusercontent.com/34289614/42821920-0a05166c-8a1d-11e8-8d8d-1bb5dbd8932b.png">

**Comment by ajmalsiddiqui** [comment]
Sorry, I didn't realise that this was an issue with the backend. I'll open an issue in the xi-editor repo. Thanks a lot for the snap showing the bug with xi-mac as the frontend. :)
