### ISSUE TITLE
Is this product still actively maintained

### ISSUE THREAD

**Issue by herman-rogers** [acheronfail/xi-electron#20]
Hello - was just wondering if this project is still being maintained and if so what is the Roadmap? Would like to fire up a speedy editor for my web development work.

**Comment by acheronfail** [comment]
> Hello - was just wondering if this project is still being maintained and if so what is the Roadmap? Would like to fire up a speedy editor for my web development work.

1. I wouldn't say that this is a "product"! haha more like a little side experiment
2. If you're looking for a speedy editor, and you want it to be based of `xi-editor`, then I would be looking at its only official frontend: https://github.com/google/xi-mac
